spring:
  datasource:
    url: jdbc:h2:tcp://localhost/~/dyshop
    username: sa
    password:
    driver-class-name: org.h2.Driver

  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
#        show_sql: true // systemout log
        format_sql: true

logging.level:
  org.hibernate.SQL: debug
    # org.hibernate.type: trace